weight: 1
disabled: false
languageCode: "es"
languageName: "Español"
title: "Learn-Software.com"
params:
  displayName: "ES"
  isoCode: "es"
  rtl: false
  dateFormat: "02 January 2006"
  description: "Impulsa tu carrera"
  copyright: "© 2022-{ year } Julian Nonino. Todos los derechos reservados."
  logo: "img/logo.jpeg"
  secondaryLogo: "img/secondary-logo.jpeg"
  author:
    name: "Learn-Software.com"
    headline: "Aprende. Crea. Domina."
    email: "learn.software.eng@gmail.com"
    image: "img/avatar.png"
    imageQuality: 96
    links:
      - email: "mailto:learn.software.eng@gmail.com"
      - github: "https://github.com/learn-software-engineering"
      - patreon: "https://patreon.com/learnsoftwareeng"
      - linkedin: "https://linkedin.com/company/learn-software"
      - instagram: "https://www.instagram.com/learnsoftwareeng"
      - facebook: "https://www.facebook.com/learn.software.eng"
      - x-twitter: "https://x.com/software45687"
      - youtube: "https://www.youtube.com/@learn-software"
#       - link: "https://link-to-some-website.com/"
#       - amazon: "https://www.amazon.com/hz/wishlist/ls/wishlist-id"
#       - apple: "https://www.apple.com"
#       - blogger: "https://username.blogspot.com/"
#       - bluesky: "https://bsky.app/profile/username"
#       - codepen: "https://codepen.io/username"
#       - dev: "https://dev.to/username"
#       - discord: "https://discord.gg/invitecode"
#       - dribbble: "https://dribbble.com/username"
#       - flickr: "https://www.flickr.com/photos/username/"
#       - foursquare: "https://foursquare.com/username"
#       - gitlab: "https://gitlab.com/username"
#       - google: "https://www.google.com/"
#       - hashnode: "https://username.hashnode.dev"
#       - itch-io: "https://username.itch.io"
#       - keybase: "https://keybase.io/username"
#       - kickstarter: "https://www.kickstarter.com/profile/username"
#       - lastfm: "https://lastfm.com/user/username"
#       - mastodon: "https://mastodon.instance/@username"
#       - medium: "https://medium.com/username"
#       - microsoft: "https://www.microsoft.com/"
#       - orcid: "https://orcid.org/userid"
#       - pinterest: "https://pinterest.com/username"
#       - reddit: "https://reddit.com/user/username"
#       - researchgate: "https://www.researchgate.net/profile/username"
#       - slack: "https://workspace.url/team/userid"
#       - snapchat: "https://snapchat.com/add/username"
#       - soundcloud: "https://soundcloud.com/username"
#       - spotify: "https://open.spotify.com/user/userid"
#       - stack-overflow: "https://stackoverflow.com/users/userid/username"
#       - steam: "https://steamcommunity.com/profiles/userid"
#       - telegram: "https://t.me/username"
#       - threads: "https://www.threads.net/@username"
#       - tiktok: "https://tiktok.com/@username"
#       - tumblr: "https://username.tumblr.com"
#       - twitch: "https://twitch.tv/username"
#       - twitter: "https://x.com/software45687"
#       - whatsapp: "https://wa.me/phone-number"
#       - ko-fi: "https://ko-fi.com/username"
#       - codeberg: "https://codeberg.org/username"
