name: PR Workflow

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

jobs:
  spell-checker:
    runs-on: ubuntu-latest
    container: ghcr.io/cn-writing/cspell
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: CSpell
        run: task spell-check
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/cn-docker/hugo
    env:
      ENV: development
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Build with Hugo
        run: task build ENV=development
